// API client for Lead Scout CRM
// All endpoints are relative to /api/

const API_BASE = '/api'

// Helper to make API calls
async function apiCall<T>(
  method: 'GET' | 'POST' | 'PUT' | 'DELETE',
  endpoint: string,
  body?: any
): Promise<T> {
  const options: RequestInit = {
    method,
    headers: {
      'Content-Type': 'application/json',
    },
  }

  if (body) {
    options.body = JSON.stringify(body)
  }

  const response = await fetch(`${API_BASE}${endpoint}`, options)

  if (!response.ok) {
    throw new Error(`API error: ${response.status}`)
  }

  if (response.status === 204) {
    return {} as T
  }

  return response.json()
}

// Types
export interface Thread {
  id: string
  tenantId: string
  title: string
  url: string
  platform: string
  content: string
  relevanceScore: number
  status: 'new' | 'reviewed' | 'responded' | 'dismissed'
  sourceId: string
  createdAt: string
  updatedAt: string
}

export interface Company {
  id: string
  tenantId: string
  name: string
  domain?: string
  industry?: string
  sizeEstimate?: string
  status: 'new' | 'researched' | 'contacted' | 'qualified' | 'disqualified'
  notes?: string
  createdAt: string
  updatedAt: string
}

export interface Lead {
  id: string
  tenantId: string
  name: string
  email?: string
  role?: string
  handle?: string
  companyId?: string
  status: 'new' | 'contacted' | 'engaged' | 'converted' | 'inactive'
  leadType: 'community' | 'prospect' | 'company' | 'engaged'
  signal?: string
  signalStrength: 'hot' | 'warm' | 'cold'
  sourceUrl?: string
  relevanceScore?: number
  platform?: string
  notes?: string
  createdAt: string
  updatedAt: string
}

export interface Response {
  id: string
  tenantId: string
  threadId: string
  draftText: string
  tone: 'helpful' | 'technical' | 'casual'
  status: 'draft' | 'approved' | 'posted' | 'rejected'
  autoGenerated: boolean
  scheduledPostAt?: string
  platform?: string
  parentUrl?: string
  postedAt?: string
  createdAt: string
  updatedAt: string
}

export interface Knowledge {
  id: string
  tenantId: string
  category: string
  title: string
  content: string
  createdAt: string
  updatedAt: string
}

export interface Scan {
  id: string
  tenantId: string
  sourceId: string
  scanType: string
  status: 'pending' | 'running' | 'completed' | 'failed'
  threadsFound: number
  startedAt: string
  completedAt?: string
  createdAt: string
  updatedAt: string
}

export interface Source {
  id: string
  tenantId: string
  name: string
  platform: string
  url: string
  active: boolean
  createdAt: string
  updatedAt: string
}

export interface MediaAsset {
  id: string
  tenantId: string
  sourceId?: string
  name: string
  handle?: string
  platform: string
  url: string
  assetType: string
  description?: string
  followerCount?: number
  metrics?: string
  isActive: boolean
  lastCheckedAt?: string
  createdAt: string
  updatedAt: string
}

export interface MediaMetric {
  id: string
  mediaAssetId: string
  followers: number
  stars: number
  engagement: number
  recordedAt: string
  createdAt: string
  updatedAt: string
}

export interface EngagementEvent {
  id: string
  tenantId: string
  mediaAssetId: string
  eventType: 'star' | 'comment' | 'share' | 'follow'
  actor: string
  actorHandle?: string
  actorPlatform?: string
  content?: string
  url?: string
  eventAt: string
  createdAt: string
  updatedAt: string
}

export interface Stats {
  totalThreads: number
  totalCompanies: number
  totalLeads: number
  responseRate: number
  threadsThisWeek: number
  companiesThisWeek: number
}

// Threads
export const threadsApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<Thread[]>(
      'GET',
      `/tenants/${tenantId}/threads?${new URLSearchParams(filters || {}).toString()}`
    ),
  get: (tenantId: string, threadId: string) =>
    apiCall<Thread>('GET', `/tenants/${tenantId}/threads/${threadId}`),
  update: (tenantId: string, threadId: string, data: Partial<Thread>) =>
    apiCall<Thread>('PUT', `/tenants/${tenantId}/threads/${threadId}`, data),
  delete: (tenantId: string, threadId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/threads/${threadId}`),
}

// Companies
export const companiesApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<Company[]>(
      'GET',
      `/tenants/${tenantId}/companies?${new URLSearchParams(filters || {}).toString()}`
    ),
  get: (tenantId: string, companyId: string) =>
    apiCall<Company>('GET', `/tenants/${tenantId}/companies/${companyId}`),
  create: (tenantId: string, data: Omit<Company, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Company>('POST', `/tenants/${tenantId}/companies`, data),
  update: (tenantId: string, companyId: string, data: Partial<Company>) =>
    apiCall<Company>('PUT', `/tenants/${tenantId}/companies/${companyId}`, data),
  delete: (tenantId: string, companyId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/companies/${companyId}`),
}

// Leads
export const leadsApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<Lead[]>(
      'GET',
      `/tenants/${tenantId}/leads?${new URLSearchParams(filters || {}).toString()}`
    ),
  get: (tenantId: string, leadId: string) =>
    apiCall<Lead>('GET', `/tenants/${tenantId}/leads/${leadId}`),
  create: (tenantId: string, data: Omit<Lead, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Lead>('POST', `/tenants/${tenantId}/leads`, data),
  update: (tenantId: string, leadId: string, data: Partial<Lead>) =>
    apiCall<Lead>('PUT', `/tenants/${tenantId}/leads/${leadId}`, data),
  delete: (tenantId: string, leadId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/leads/${leadId}`),
}

// Responses
export const responsesApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<Response[]>(
      'GET',
      `/tenants/${tenantId}/responses?${new URLSearchParams(filters || {}).toString()}`
    ),
  get: (tenantId: string, responseId: string) =>
    apiCall<Response>('GET', `/tenants/${tenantId}/responses/${responseId}`),
  create: (tenantId: string, data: Omit<Response, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Response>('POST', `/tenants/${tenantId}/responses`, data),
  update: (tenantId: string, responseId: string, data: Partial<Response>) =>
    apiCall<Response>('PUT', `/tenants/${tenantId}/responses/${responseId}`, data),
  send: (tenantId: string, responseId: string) =>
    apiCall<Response>('POST', `/tenants/${tenantId}/responses/${responseId}/send`, {}),
  delete: (tenantId: string, responseId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/responses/${responseId}`),
}

// Knowledge
export const knowledgeApi = {
  list: (tenantId: string, category?: string) =>
    apiCall<Knowledge[]>(
      'GET',
      `/tenants/${tenantId}/knowledge${category ? `?category=${category}` : ''}`
    ),
  get: (tenantId: string, knowledgeId: string) =>
    apiCall<Knowledge>('GET', `/tenants/${tenantId}/knowledge/${knowledgeId}`),
  create: (tenantId: string, data: Omit<Knowledge, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Knowledge>('POST', `/tenants/${tenantId}/knowledge`, data),
  update: (tenantId: string, knowledgeId: string, data: Partial<Knowledge>) =>
    apiCall<Knowledge>('PUT', `/tenants/${tenantId}/knowledge/${knowledgeId}`, data),
  delete: (tenantId: string, knowledgeId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/knowledge/${knowledgeId}`),
}

// Scans
export const scansApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<Scan[]>(
      'GET',
      `/tenants/${tenantId}/scans?${new URLSearchParams(filters || {}).toString()}`
    ),
  get: (tenantId: string, scanId: string) =>
    apiCall<Scan>('GET', `/tenants/${tenantId}/scans/${scanId}`),
  create: (tenantId: string, data: Omit<Scan, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Scan>('POST', `/tenants/${tenantId}/scans`, data),
  update: (tenantId: string, scanId: string, data: Partial<Scan>) =>
    apiCall<Scan>('PUT', `/tenants/${tenantId}/scans/${scanId}`, data),
}

// Sources
export const sourcesApi = {
  list: (tenantId: string) =>
    apiCall<Source[]>('GET', `/tenants/${tenantId}/sources`),
  get: (tenantId: string, sourceId: string) =>
    apiCall<Source>('GET', `/tenants/${tenantId}/sources/${sourceId}`),
  create: (tenantId: string, data: Omit<Source, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<Source>('POST', `/tenants/${tenantId}/sources`, data),
  update: (tenantId: string, sourceId: string, data: Partial<Source>) =>
    apiCall<Source>('PUT', `/tenants/${tenantId}/sources/${sourceId}`, data),
  delete: (tenantId: string, sourceId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/sources/${sourceId}`),
}

// Media Assets
export const mediaAssetsApi = {
  list: (tenantId: string) =>
    apiCall<MediaAsset[]>('GET', `/tenants/${tenantId}/media-assets`),
  get: (tenantId: string, assetId: string) =>
    apiCall<MediaAsset>('GET', `/tenants/${tenantId}/media-assets/${assetId}`),
  create: (tenantId: string, data: Omit<MediaAsset, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<MediaAsset>('POST', `/tenants/${tenantId}/media-assets`, data),
  update: (tenantId: string, assetId: string, data: Partial<MediaAsset>) =>
    apiCall<MediaAsset>('PUT', `/tenants/${tenantId}/media-assets/${assetId}`, data),
  delete: (tenantId: string, assetId: string) =>
    apiCall<void>('DELETE', `/tenants/${tenantId}/media-assets/${assetId}`),
}

// Media Metrics
export const mediaMetricsApi = {
  list: (tenantId: string, mediaAssetId?: string) =>
    apiCall<MediaMetric[]>(
      'GET',
      `/tenants/${tenantId}/media-metrics${mediaAssetId ? `?mediaAssetId=${mediaAssetId}` : ''}`
    ),
  getTrends: (tenantId: string, mediaAssetId: string, days?: number) =>
    apiCall<MediaMetric[]>(
      'GET',
      `/tenants/${tenantId}/media-assets/${mediaAssetId}/trends${days ? `?days=${days}` : ''}`
    ),
  create: (tenantId: string, data: Omit<MediaMetric, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<MediaMetric>('POST', `/tenants/${tenantId}/media-metrics`, data),
}

// Engagement Events
export const engagementEventsApi = {
  list: (tenantId: string, filters?: any) =>
    apiCall<EngagementEvent[]>(
      'GET',
      `/tenants/${tenantId}/engagement-events?${new URLSearchParams(filters || {}).toString()}`
    ),
  getRecent: (tenantId: string, mediaAssetId: string, limit?: number) =>
    apiCall<EngagementEvent[]>(
      'GET',
      `/tenants/${tenantId}/media-assets/${mediaAssetId}/engagement${limit ? `?limit=${limit}` : ''}`
    ),
  create: (tenantId: string, data: Omit<EngagementEvent, 'id' | 'createdAt' | 'updatedAt'>) =>
    apiCall<EngagementEvent>('POST', `/tenants/${tenantId}/engagement-events`, data),
  convertToLead: (tenantId: string, eventId: string) =>
    apiCall<Lead>(
      'POST',
      `/tenants/${tenantId}/engagement-events/${eventId}/convert-to-lead`,
      {}
    ),
}

// Stats
export const statsApi = {
  get: (tenantId: string) =>
    apiCall<Stats>('GET', `/tenants/${tenantId}/stats`),
}
