name = "lead-scout"
compatibility_date = "2024-06-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "lead-scout-db"
database_id = "926f3622-a11e-4c94-aea3-0d633bed8d43"
migrations_dir = "drizzle"

[ai]
binding = "AI"

# [vars]
# ENVIRONMENT = "production"
