import { describe, it, expect } from "vitest";
import { getTableName } from "drizzle-orm";
import {
  tenants,
  sources,
  threads,
  companies,
  leads,
  responses,
  knowledge,
  scanLogs,
  mediaAssets,
  mediaMetricSnapshots,
  engagementEvents,
} from "../db/schema";

describe("Database Schema", () => {
  describe("tenants table", () => {
    it("should have correct table name", () => {
      expect(getTableName(tenants)).toBe("tenants");
    });

    it("should have required columns", () => {
      const cols = Object.keys(tenants);
      expect(cols).toContain("id");
      expect(cols).toContain("name");
      expect(cols).toContain("description");
      expect(cols).toContain("createdAt");
      expect(cols).toContain("updatedAt");
    });
  });

  describe("sources table", () => {
    it("should have correct table name", () => {
      expect(getTableName(sources)).toBe("sources");
    });

    it("should have tenant isolation column", () => {
      expect(Object.keys(sources)).toContain("tenantId");
    });

    it("should have source type and keywords columns", () => {
      const cols = Object.keys(sources);
      expect(cols).toContain("sourceType");
      expect(cols).toContain("keywords");
      expect(cols).toContain("platform");
      expect(cols).toContain("scanConfig");
    });
  });

  describe("threads table", () => {
    it("should have correct table name", () => {
      expect(getTableName(threads)).toBe("threads");
    });

    it("should have all required columns", () => {
      const cols = Object.keys(threads);
      expect(cols).toContain("tenantId");
      expect(cols).toContain("sourceId");
      expect(cols).toContain("url");
      expect(cols).toContain("platform");
      expect(cols).toContain("relevanceScore");
      expect(cols).toContain("status");
      expect(cols).toContain("discoveredAt");
    });
  });

  describe("leads table", () => {
    it("should have correct table name", () => {
      expect(getTableName(leads)).toBe("leads");
    });

    it("should have lead type fields", () => {
      const cols = Object.keys(leads);
      expect(cols).toContain("leadType");
      expect(cols).toContain("signal");
      expect(cols).toContain("signalStrength");
      expect(cols).toContain("sourceUrl");
    });

    it("should have optional company reference", () => {
      expect(Object.keys(leads)).toContain("companyId");
    });
  });

  describe("companies table", () => {
    it("should have correct table name", () => {
      expect(getTableName(companies)).toBe("companies");
    });

    it("should have required columns", () => {
      const cols = Object.keys(companies);
      expect(cols).toContain("tenantId");
      expect(cols).toContain("name");
      expect(cols).toContain("sizeEstimate");
      expect(cols).toContain("status");
    });
  });

  describe("responses table", () => {
    it("should have automation fields", () => {
      const cols = Object.keys(responses);
      expect(cols).toContain("autoGenerated");
      expect(cols).toContain("scheduledPostAt");
      expect(cols).toContain("platform");
      expect(cols).toContain("parentUrl");
    });

    it("should link to threads", () => {
      expect(Object.keys(responses)).toContain("threadId");
    });
  });

  describe("knowledge table", () => {
    it("should have correct table name", () => {
      expect(getTableName(knowledge)).toBe("knowledge");
    });

    it("should have category and tags", () => {
      const cols = Object.keys(knowledge);
      expect(cols).toContain("category");
      expect(cols).toContain("tags");
    });
  });

  describe("scanLogs table", () => {
    it("should have correct table name", () => {
      expect(getTableName(scanLogs)).toBe("scan_logs");
    });

    it("should track scan stats", () => {
      const cols = Object.keys(scanLogs);
      expect(cols).toContain("threadsFound");
      expect(cols).toContain("companiesFound");
      expect(cols).toContain("leadsFound");
      expect(cols).toContain("status");
    });
  });

  describe("mediaAssets table", () => {
    it("should have correct table name", () => {
      expect(getTableName(mediaAssets)).toBe("media_assets");
    });

    it("should have asset tracking fields", () => {
      const cols = Object.keys(mediaAssets);
      expect(cols).toContain("platform");
      expect(cols).toContain("assetType");
      expect(cols).toContain("handle");
      expect(cols).toContain("followerCount");
      expect(cols).toContain("metrics");
    });
  });

  describe("mediaMetricSnapshots table", () => {
    it("should have correct table name", () => {
      expect(getTableName(mediaMetricSnapshots)).toBe(
        "media_metric_snapshots"
      );
    });

    it("should track metric history", () => {
      const cols = Object.keys(mediaMetricSnapshots);
      expect(cols).toContain("mediaAssetId");
      expect(cols).toContain("snapshotDate");
      expect(cols).toContain("followers");
      expect(cols).toContain("stars");
      expect(cols).toContain("engagementRate");
    });
  });

  describe("engagementEvents table", () => {
    it("should have correct table name", () => {
      expect(getTableName(engagementEvents)).toBe("engagement_events");
    });

    it("should track engagement with lead conversion", () => {
      const cols = Object.keys(engagementEvents);
      expect(cols).toContain("eventType");
      expect(cols).toContain("actorHandle");
      expect(cols).toContain("actorProfileUrl");
      expect(cols).toContain("convertedToLeadId");
    });
  });

  describe("multi-tenancy", () => {
    it("all data tables should have tenantId column", () => {
      const dataTables = [
        { table: sources, name: "sources" },
        { table: threads, name: "threads" },
        { table: companies, name: "companies" },
        { table: leads, name: "leads" },
        { table: responses, name: "responses" },
        { table: knowledge, name: "knowledge" },
        { table: scanLogs, name: "scanLogs" },
        { table: mediaAssets, name: "mediaAssets" },
        { table: mediaMetricSnapshots, name: "mediaMetricSnapshots" },
        { table: engagementEvents, name: "engagementEvents" },
      ];

      for (const { table, name } of dataTables) {
        expect(
          Object.keys(table),
          `${name} should have tenantId`
        ).toContain("tenantId");
      }
    });
  });
});
