import React, { useState, useEffect } from 'react'
import { Send, Edit, Trash2, MessageSquare, Bot, ExternalLink, Calendar } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { responsesApi, threadsApi, Response, Thread } from '@/lib/api'

interface ResponsesProps {
  tenantId: string
}

const STATUS_GROUPS = ['draft', 'scheduled', 'posted', 'rejected'] as const

export default function Responses({ tenantId }: ResponsesProps) {
  const [responses, setResponses] = useState<Response[]>([])
  const [threads, setThreads] = useState<Thread[]>([])
  const [filteredResponses, setFilteredResponses] = useState<Response[]>([])
  const [loading, setLoading] = useState(true)
  const [showDialog, setShowDialog] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)

  // Filters
  const [statusFilter, setStatusFilter] = useState('all')

  // Form state
  const [formData, setFormData] = useState({
    threadId: '',
    responseContent: '',
    status: 'draft' as const,
    autoGenerated: false,
    scheduledPostAt: '',
    platform: '',
    parentUrl: '',
  })

  useEffect(() => {
    const loadData = async () => {
      try {
        const [responsesData, threadsData] = await Promise.all([
          responsesApi.list(tenantId),
          threadsApi.list(tenantId),
        ])
        setResponses(responsesData)
        setThreads(threadsData)
      } catch (error) {
        console.error('Failed to load data:', error)
      } finally {
        setLoading(false)
      }
    }
    loadData()
  }, [tenantId])

  useEffect(() => {
    let filtered = responses

    if (statusFilter !== 'all') {
      filtered = filtered.filter((r) => r.status === statusFilter)
    }

    setFilteredResponses(filtered)
  }, [responses, statusFilter])

  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case 'draft':
        return 'yellow'
      case 'scheduled':
        return 'blue'
      case 'posted':
        return 'green'
      case 'rejected':
        return 'gray'
      default:
        return 'default'
    }
  }

  const getThreadTitle = (threadId: string) => {
    return threads.find((t) => t.id === threadId)?.title || 'Unknown thread'
  }

  const resetForm = () => {
    setFormData({
      threadId: '',
      responseContent: '',
      status: 'draft',
      autoGenerated: false,
      scheduledPostAt: '',
      platform: '',
      parentUrl: '',
    })
    setEditingId(null)
  }

  const handleOpenDialog = (response?: Response) => {
    if (response) {
      setFormData({
        threadId: response.threadId,
        responseContent: response.responseContent,
        status: response.status,
        autoGenerated: response.autoGenerated,
        scheduledPostAt: response.scheduledPostAt || '',
        platform: response.platform || '',
        parentUrl: response.parentUrl || '',
      })
      setEditingId(response.id)
    } else {
      resetForm()
    }
    setShowDialog(true)
  }

  const handleSubmit = async () => {
    try {
      if (editingId) {
        await responsesApi.update(tenantId, editingId, formData)
        setResponses(
          responses.map((r) => (r.id === editingId ? { ...r, ...formData } : r))
        )
      } else {
        const newResponse = await responsesApi.create(tenantId, {
          tenantId,
          ...formData,
          respondedAt: new Date().toISOString(),
        })
        setResponses([...responses, newResponse])
      }
      setShowDialog(false)
      resetForm()
    } catch (error) {
      console.error('Failed to save response:', error)
    }
  }

  const handleSend = async (id: string) => {
    try {
      await responsesApi.send(tenantId, id)
      setResponses(
        responses.map((r) => (r.id === id ? { ...r, status: 'posted' } : r))
      )
    } catch (error) {
      console.error('Failed to send response:', error)
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await responsesApi.delete(tenantId, id)
      setResponses(responses.filter((r) => r.id !== id))
    } catch (error) {
      console.error('Failed to delete response:', error)
    }
  }

  if (loading) {
    return (
      <div className="flex-1 overflow-auto p-8">
        <div className="text-center text-muted-foreground">Loading responses...</div>
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-auto">
      <div className="p-8 space-y-6">
        {/* Header with Add Button */}
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm text-muted-foreground">
              {filteredResponses.length} responses
            </p>
          </div>
          <Button onClick={() => handleOpenDialog()}>
            <MessageSquare className="w-4 h-4 mr-2" />
            Compose Response
          </Button>
        </div>

        {/* Status Tabs */}
        <div className="flex gap-2 border-b border-border pb-4 overflow-x-auto">
          <button
            onClick={() => setStatusFilter('all')}
            className={`px-4 py-2 text-sm font-medium whitespace-nowrap transition-colors ${
              statusFilter === 'all'
                ? 'border-b-2 border-accent text-accent'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            All
          </button>
          {STATUS_GROUPS.map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={`px-4 py-2 text-sm font-medium whitespace-nowrap transition-colors capitalize ${
                statusFilter === status
                  ? 'border-b-2 border-accent text-accent'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {status}
            </button>
          ))}
        </div>

        {/* Responses List */}
        <div className="space-y-3">
          {filteredResponses.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <p className="text-muted-foreground">No responses found</p>
              </CardContent>
            </Card>
          ) : (
            filteredResponses.map((response) => (
              <Card key={response.id} className="hover:border-accent transition-colors">
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <h3 className="text-lg font-semibold">
                            {getThreadTitle(response.threadId)}
                          </h3>
                          {response.autoGenerated && (
                            <Badge variant="blue" className="text-xs flex items-center gap-1">
                              <Bot className="w-3 h-3" />
                              AI Generated
                            </Badge>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground">
                          {new Date(response.respondedAt).toLocaleString()}
                        </p>
                        {response.platform && (
                          <p className="text-xs text-muted-foreground mt-1">
                            Platform: {response.platform}
                          </p>
                        )}
                      </div>
                      <Badge variant={getStatusBadgeVariant(response.status)}>
                        {response.status}
                      </Badge>
                    </div>

                    <div className="p-4 rounded-md bg-muted border border-border">
                      <p className="text-sm whitespace-pre-wrap">
                        {response.responseContent}
                      </p>
                    </div>

                    {/* Parent URL */}
                    {response.parentUrl && (
                      <a
                        href={response.parentUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-accent hover:underline text-xs flex items-center gap-1"
                      >
                        <ExternalLink className="w-3 h-3" />
                        {response.parentUrl}
                      </a>
                    )}

                    {/* Scheduled Info */}
                    {response.scheduledPostAt && (
                      <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/50 rounded px-3 py-2">
                        <Calendar className="w-3 h-3" />
                        Scheduled for {new Date(response.scheduledPostAt).toLocaleString()}
                      </div>
                    )}

                    <div className="flex items-center gap-2 justify-end flex-wrap">
                      {response.status === 'draft' && (
                        <>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handleOpenDialog(response)}
                          >
                            <Edit className="w-4 h-4 mr-2" />
                            Edit
                          </Button>
                          <Button
                            size="sm"
                            onClick={() => handleSend(response.id)}
                          >
                            <Send className="w-4 h-4 mr-2" />
                            Send
                          </Button>
                        </>
                      )}
                      {response.status === 'scheduled' && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleOpenDialog(response)}
                        >
                          <Edit className="w-4 h-4 mr-2" />
                          Reschedule
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDelete(response.id)}
                      >
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>

      {/* Compose/Edit Response Dialog */}
      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>
              {editingId ? 'Edit Response' : 'Compose Response'}
            </DialogTitle>
            <DialogDescription>
              {editingId
                ? 'Update your response draft'
                : 'Create a new response to a thread'}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 max-h-[60vh] overflow-y-auto">
            <div>
              <label className="text-sm font-medium">Thread</label>
              <Select
                value={formData.threadId}
                onChange={(e) => setFormData({ ...formData, threadId: e.target.value })}
              >
                <option value="">Select a thread</option>
                {threads.map((t) => (
                  <option key={t.id} value={t.id}>
                    {t.title}
                  </option>
                ))}
              </Select>
            </div>

            <div>
              <label className="text-sm font-medium">Response</label>
              <Textarea
                value={formData.responseContent}
                onChange={(e) =>
                  setFormData({ ...formData, responseContent: e.target.value })
                }
                placeholder="Write your response here..."
                rows={8}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium">Platform</label>
                <Input
                  value={formData.platform}
                  onChange={(e) => setFormData({ ...formData, platform: e.target.value })}
                  placeholder="e.g., Twitter, LinkedIn"
                />
              </div>

              <div>
                <label className="text-sm font-medium">Status</label>
                <Select
                  value={formData.status}
                  onChange={(e) =>
                    setFormData({ ...formData, status: e.target.value as any })
                  }
                >
                  <option value="draft">Draft</option>
                  <option value="scheduled">Scheduled</option>
                  <option value="posted">Posted</option>
                  <option value="rejected">Rejected</option>
                </Select>
              </div>
            </div>

            <div>
              <label className="text-sm font-medium">Parent URL</label>
              <Input
                type="url"
                value={formData.parentUrl}
                onChange={(e) => setFormData({ ...formData, parentUrl: e.target.value })}
                placeholder="https://..."
              />
            </div>

            {formData.status === 'scheduled' && (
              <div>
                <label className="text-sm font-medium">Schedule Post For</label>
                <Input
                  type="datetime-local"
                  value={formData.scheduledPostAt}
                  onChange={(e) =>
                    setFormData({ ...formData, scheduledPostAt: e.target.value })
                  }
                />
              </div>
            )}

            <div className="flex items-center gap-3 p-3 bg-muted/50 rounded-md">
              <input
                type="checkbox"
                id="autoGenerated"
                checked={formData.autoGenerated}
                onChange={(e) =>
                  setFormData({ ...formData, autoGenerated: e.target.checked })
                }
                className="w-4 h-4"
              />
              <label htmlFor="autoGenerated" className="text-sm font-medium cursor-pointer">
                This response was AI-generated
              </label>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleSubmit}>
              {editingId ? 'Update' : 'Save'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
