import { Hono } from 'hono';
import { ulid } from 'ulid';
import { eq, and, desc, sql } from 'drizzle-orm';
import { Bindings, Variables } from '../index';
import { responses } from '../../db/schema';
import { createDb } from '../../db';

const router = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// POST / - Create draft response
router.post('/', async (c) => {
  try {
    const tenantId = c.get('tenantId');
    const body = await c.req.json();
    const {
      thread_id,
      lead_id,
      subject,
      body: responseBody,
      template_id,
      autoGenerated,
      scheduledPostAt,
      platform,
      parentUrl,
    } = body;

    if (!thread_id) {
      return c.json({ error: 'thread_id required' }, 400);
    }

    const db = createDb(c.env.DB);

    const responseId = ulid();
    const now = new Date();

    await db.insert(responses).values({
      id: responseId,
      tenantId,
      threadId: thread_id,
      draftText: responseBody || '',
      tone: 'helpful',
      status: 'draft',
      autoGenerated: autoGenerated || false,
      scheduledPostAt: scheduledPostAt ? new Date(scheduledPostAt) : null,
      platform: platform || null,
      parentUrl: parentUrl || null,
      createdAt: now,
      updatedAt: now,
    });

    return c.json(
      {
        id: responseId,
        tenantId,
        threadId: thread_id,
        draftText: responseBody,
        tone: 'helpful',
        status: 'draft',
        autoGenerated: autoGenerated || false,
        scheduledPostAt,
        platform,
        parentUrl,
        createdAt: now.toISOString(),
      },
      201
    );
  } catch (error) {
    console.error('Error creating response:', error);
    return c.json({ error: 'Failed to create response' }, 500);
  }
});

// GET / - List responses with filters
router.get('/', async (c) => {
  try {
    const tenantId = c.get('tenantId');
    const thread_id = c.req.query('thread_id');
    const status = c.req.query('status');
    const autoGenerated = c.req.query('autoGenerated');
    const platform = c.req.query('platform');
    const limit = Math.min(parseInt(c.req.query('limit') || '50'), 100);
    const offset = parseInt(c.req.query('offset') || '0');

    const db = createDb(c.env.DB);

    const conditions = [eq(responses.tenantId, tenantId)];

    if (thread_id) {
      conditions.push(eq(responses.threadId, thread_id));
    }
    if (status) {
      conditions.push(eq(responses.status, status as any));
    }
    if (autoGenerated !== undefined) {
      conditions.push(eq(responses.autoGenerated, autoGenerated === 'true'));
    }
    if (platform) {
      conditions.push(eq(responses.platform, platform as any));
    }

    const result = await db
      .select()
      .from(responses)
      .where(and(...conditions))
      .orderBy(desc(responses.createdAt))
      .limit(limit)
      .offset(offset);

    const countResult = await db
      .select({ count: sql<number>`COUNT(*)` })
      .from(responses)
      .where(and(...conditions));

    const total = countResult[0]?.count || 0;

    return c.json({
      data: result,
      pagination: {
        limit,
        offset,
        total,
        hasMore: offset + limit < total,
      },
    });
  } catch (error) {
    console.error('Error listing responses:', error);
    return c.json({ error: 'Failed to list responses' }, 500);
  }
});

// PATCH /:id - Update response
router.patch('/:id', async (c) => {
  try {
    const tenantId = c.get('tenantId');
    const id = c.req.param('id');
    const body = await c.req.json();
    const { subject, body: responseBody, status, scheduledPostAt } = body;

    const db = createDb(c.env.DB);

    const existing = await db
      .select()
      .from(responses)
      .where(and(eq(responses.id, id), eq(responses.tenantId, tenantId)))
      .limit(1);

    if (existing.length === 0) {
      return c.json({ error: 'Response not found' }, 404);
    }

    const updateData: Record<string, any> = {
      updatedAt: new Date(),
    };

    if (responseBody !== undefined) updateData.draftText = responseBody;
    if (status !== undefined) updateData.status = status;
    if (scheduledPostAt !== undefined) {
      updateData.scheduledPostAt = scheduledPostAt
        ? new Date(scheduledPostAt)
        : null;
    }

    await db.update(responses).set(updateData).where(eq(responses.id, id));

    const updated = await db
      .select()
      .from(responses)
      .where(eq(responses.id, id))
      .limit(1);

    return c.json(updated[0]);
  } catch (error) {
    console.error('Error updating response:', error);
    return c.json({ error: 'Failed to update response' }, 500);
  }
});

export default router;
